export enum Role {
    SCHOOL_ADMIN = "SCHOOL_ADMIN",
    SUPER_ADMIN = "SUPER_ADMIN",
    TEACHER = "TEACHER",
    STUDENT = "STUDENT",
    PARENTS = "PARENTS",
    PRINCIPAL = "PRINCIPAL",
    ACCOUNTANT = "ACCOUNTANT"
}